### ISSUE TITLE
hardware requirement of training

### ISSUE THREAD

**Issue by argman** [Project-MONAI/VISTA#38]
what kind of hardware do you use for training ?

**Comment by heyufan1995** [comment]
All the training is performed on 32G V100. The memory usuage is largely dependent on the max_prompt (max foreground classes to train with for this iteration) since it is the actual "batch_size".  Reducing this number will reduce memory usage but take longer to converge for dataset with >100 foreground classes.

**Comment by argman** [comment]
so you use 8 v100 ?

And do you generate pesudo labels using models from total segmentator? what if the model is not accurate.
